//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.Linq;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq.Expressions;
namespace TaskFollowUp.Data
{
    public partial class SprintRepository:IRepository<Sprint>,IRepository
    {
    		DbContext _context;
            public SprintRepository(DbContext context)
            {
                _context = context ?? new ProjectConnectionString();
            }
    
            public IEnumerable<Sprint> Get(Expression<Func<Sprint, bool>> predicate, string [] relations)
            {
                    var query = _context.Set<Sprint>().Select(s=>s);
                    if (relations != null)
                    foreach (var rel in relations)
                    {
                      query=  query.Include(rel);
                    }
    
                    return (predicate!=null ? query.Where(predicate) : query).ToList();        
                }
    
    		public Sprint GetById(Expression<Func<Sprint, bool>> predicate, string [] relations, int Id)
            {
    				var query = _context.Set<Sprint>().Select(s=>s);
                    if (relations!=null)
                    foreach (var rel in relations)
                    {
                      query=  query.Include(rel);
                    }
                return (predicate!=null? query.Where(predicate) : query).FirstOrDefault(s => s.Id == Id);
            }
    
            public void Save(List<Sprint> entities)
            {
                foreach(var entity in entities)
    			{
    				SetState(entity);
    			}
    			_context.SaveChanges();
            }
    
            public void Save(Sprint entity)
            {
                SetState(entity);
    			
    			_context.SaveChanges();
            }
    
            public void Delete(Sprint entity)
            {
                _context.Set<Sprint>().Remove(entity);
    			
    			_context.SaveChanges();
            }
    
            public void DeleteById(int Id)
            {
               var entity= _context.Set<Sprint>().FirstOrDefault(s => s.Id == Id);
    
    		   Delete(entity);
            }
    
    		 private void SetState(Sprint entity)
             {
                    _context.Entry(entity).State = entity.Id <= 0 ? EntityState.Added : EntityState.Modified;
             }
    }
}
