//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.Linq;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq.Expressions;
namespace TaskFollowUpData
{
    public partial class TaskRepository:IRepository<Task>,IRepository
    {
    		DbContext _context;
            public TaskRepository(DbContext context)
            {
                _context = context ?? new TaskFollowUpModelContainer();
            }
    
            public IEnumerable<Task> Get(Expression<Func<Task, bool>> predicate, string [] relations)
            {
                    var query = _context.Set<Task>().Select(s=>s);
                    foreach (var rel in relations)
                    {
                      query=  query.Include(rel);
                    }
    
                    return (predicate!=null ? query.Where(predicate) : query).ToList();        
                }
    
    		public Task GetById(Expression<Func<Task, bool>> predicate, string [] relations, int Id)
            {
    				var query = _context.Set<Task>().Select(s=>s);;
                    foreach (var rel in relations)
                    {
                      query=  query.Include(rel);
                    }
                return (predicate!=null? query.Where(predicate) : query).FirstOrDefault(s => s.Id == Id);
            }
    
            public void Save(List<Task> entities)
            {
                foreach(var entity in entities)
    			{
    				SetState(entity);
    			}
    			_context.SaveChanges();
            }
    
            public void Save(Task entity)
            {
                SetState(entity);
    			
    			_context.SaveChanges();
            }
    
            public void Delete(Task entity)
            {
                _context.Set<Task>().Remove(entity);
    			
    			_context.SaveChanges();
            }
    
            public void DeleteById(int Id)
            {
               var entity= _context.Set<Task>().FirstOrDefault(s => s.Id == Id);
    
    		   Delete(entity);
            }
    
    		 private void SetState(Task entity)
             {
                    _context.Entry(entity).State = entity.Id <= 0 ? EntityState.Added : EntityState.Modified;
             }
    }
}
